In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.3'

In [5]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

In [4]:
np.version.version

'1.21.3'

In [17]:
a=np.random.randint(0,100,size=(2,3,5))
print(a)

[[[72  4 23  4 55]
  [75 98 51 43 15]
  [59 70 17 89 14]]

 [[81 44 85 91 24]
  [19 17 76 67 88]
  [78 54 30 28 71]]]


In [15]:
b=np.random.random((2,3,5))
print(b)

[[[0.07981966 0.23457446 0.20144022 0.71412315 0.36210596]
  [0.43846261 0.97362101 0.69745563 0.12470983 0.13914438]
  [0.4271612  0.69268812 0.76728388 0.30723711 0.31895238]]

 [[0.08453431 0.98592799 0.68402433 0.55343046 0.27359548]
  [0.58510779 0.7239262  0.52307408 0.10366094 0.1904915 ]
  [0.42415675 0.07442651 0.50004831 0.45398378 0.83923228]]]


In [16]:
x = np.random.rand((2,3,5))

TypeError: 'tuple' object cannot be interpreted as an integer

In [24]:
b=np.full((5,2,3),1)

In [25]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [26]:
a.size == b.size

True

In [27]:
c=b.transpose(1,2,0)

In [28]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [29]:
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [31]:
d=a+c

In [32]:
print(a,d)

[[[72  4 23  4 55]
  [75 98 51 43 15]
  [59 70 17 89 14]]

 [[81 44 85 91 24]
  [19 17 76 67 88]
  [78 54 30 28 71]]] [[[73  5 24  5 56]
  [76 99 52 44 16]
  [60 71 18 90 15]]

 [[82 45 86 92 25]
  [20 18 77 68 89]
  [79 55 31 29 72]]]


In [33]:
print(a)

[[[72  4 23  4 55]
  [75 98 51 43 15]
  [59 70 17 89 14]]

 [[81 44 85 91 24]
  [19 17 76 67 88]
  [78 54 30 28 71]]]


In [34]:
print(d)

[[[73  5 24  5 56]
  [76 99 52 44 16]
  [60 71 18 90 15]]

 [[82 45 86 92 25]
  [20 18 77 68 89]
  [79 55 31 29 72]]]


In [35]:
e=a*c
print(e)

[[[72  4 23  4 55]
  [75 98 51 43 15]
  [59 70 17 89 14]]

 [[81 44 85 91 24]
  [19 17 76 67 88]
  [78 54 30 28 71]]]


In [36]:
d_max=d.max()

In [37]:
d_max

99

In [38]:
d_min=d.min()
d_mean=d.mean()

In [39]:
d_min

5

In [40]:
d_mean

52.4

In [43]:
f=np.empty((2,3,5))

In [44]:
f

array([[[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 6.90348891e-310],
        [5.02034658e+175, 1.51066862e+160, 3.56529764e-057,
         1.51899105e-047, 5.54916396e+170],
        [2.59027904e-144, 3.80985069e+180, 1.14428494e+243,
         2.59027907e-144, 7.79952704e-143]],

       [[1.10979057e-047, 2.90141814e-057, 4.15935357e-061,
         1.48971709e+161, 4.99874559e+217],
        [5.49419094e-143, 2.91237123e+257, 5.56111702e+180,
         5.74015544e+180, 1.94919988e-153],
        [2.59027858e-144, 2.59903818e-144, 4.96803199e-091,
         9.51867694e-043, 5.15249232e-062]]])

In [49]:
for i in d:
    for e in i:
        if e>d_min and e<d_mean:
        f[e]=25
    print(f)

IndentationError: expected an indented block (2223471571.py, line 4)

In [ ]:
 if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
    
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

If a value equals to d_mean, assign 50 to the corresponding value in f.

Assign 0 to the corresponding value(s) in f for d_min in d.

Assign 100 to the corresponding value(s) in f for d_max in d.

In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()